# Generated by Django 5.0 on 2023-12-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrizzleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Temp')),
                ('weather_phenomena', models.CharField(max_length=20, verbose_name='wf')),
            ],
        ),
    ]
