# Generated by Django 5.0 on 2023-12-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckWxMetar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_check_metar', models.JSONField(blank=True, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('location_api', models.CharField(blank=True, max_length=30, null=True)),
                ('location_driz', models.CharField(blank=True, max_length=30, null=True)),
                ('unix_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'check_wx_metar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForecaResponseCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_foreca', models.JSONField(blank=True, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('utc_time', models.DateTimeField(blank=True, null=True)),
                ('unix_time', models.IntegerField(blank=True, null=True)),
                ('location_api', models.CharField(blank=True, max_length=100, null=True)),
                ('location_driz', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'foreca_response_current',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeaderDrizzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.BigIntegerField(blank=True, null=True)),
                ('lon', models.BigIntegerField(blank=True, null=True)),
                ('updated_local_time', models.DateTimeField(blank=True, null=True)),
                ('unix_time', models.DateTimeField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('precip_type', models.SmallIntegerField(blank=True, null=True)),
                ('sub_type', models.SmallIntegerField(blank=True, null=True)),
                ('intensity', models.SmallIntegerField(blank=True, null=True)),
                ('prec_accum1', models.FloatField(blank=True, null=True)),
                ('prec_accum3', models.FloatField(blank=True, null=True)),
                ('prec_accum7', models.FloatField(blank=True, null=True)),
                ('precip_prob', models.FloatField(blank=True, null=True)),
                ('weather_phenomena', models.SmallIntegerField(blank=True, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('feels_like', models.FloatField(blank=True, null=True)),
                ('temp_min', models.FloatField(blank=True, null=True)),
                ('temp_max', models.FloatField(blank=True, null=True)),
                ('dew_point', models.FloatField(blank=True, null=True)),
                ('cloudnes', models.FloatField(blank=True, null=True)),
                ('polygon', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leader_drizzle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetsouResponseCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_metsou', models.JSONField()),
                ('created_time', models.DateTimeField()),
                ('utc_time', models.DateTimeField()),
                ('timezone', models.CharField(blank=True, max_length=30, null=True)),
                ('location_api', models.CharField(blank=True, max_length=100, null=True)),
                ('unix_time', models.IntegerField(blank=True, null=True)),
                ('location_driz', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'metsou_response_current',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MtcomMetarResponseCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_mtcom_metar', models.JSONField()),
                ('created_time', models.DateTimeField()),
                ('utc_time', models.DateTimeField()),
                ('location_driz', models.CharField(blank=True, max_length=100, null=True)),
                ('unix_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mtcom_metar_response_current',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NinjasRespCurr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_ninjas', models.JSONField()),
                ('created_time', models.DateTimeField()),
                ('utc_time', models.DateTimeField()),
                ('location_api', models.CharField(blank=True, max_length=100, null=True)),
                ('location_driz', models.CharField(blank=True, max_length=100, null=True)),
                ('unix_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ninjas_resp_curr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OikoRespCurr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_oiko', models.JSONField()),
                ('created_time', models.DateTimeField()),
                ('location_driz', models.CharField(blank=True, max_length=100, null=True)),
                ('unix_time', models.IntegerField(blank=True, null=True)),
                ('utc_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'oiko_resp_curr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpenMRespCurr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_open_m', models.JSONField()),
                ('created_time', models.DateTimeField()),
                ('utc_time', models.DateTimeField()),
                ('location_api', models.CharField(blank=True, max_length=100, null=True)),
                ('location_driz', models.CharField(blank=True, max_length=100, null=True)),
                ('unix_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'open_m_resp_curr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OwmResponseCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_owm', models.JSONField()),
                ('created_time', models.DateTimeField()),
                ('utc_time', models.DateTimeField()),
                ('timezone', models.SmallIntegerField()),
                ('location_api', models.CharField(blank=True, max_length=100, null=True)),
                ('location_driz', models.CharField(blank=True, max_length=100, null=True)),
                ('unix_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'owm_response_current',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SandboxDrizzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(blank=True, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('feels_like', models.FloatField(blank=True, null=True)),
                ('cloudnes', models.FloatField(blank=True, null=True)),
                ('precip_prob', models.FloatField(blank=True, null=True)),
                ('precip_type', models.SmallIntegerField(blank=True, null=True)),
                ('intensity', models.SmallIntegerField(blank=True, null=True)),
                ('prec_accum1', models.FloatField(blank=True, null=True)),
                ('prec_accum3', models.FloatField(blank=True, null=True)),
                ('prec_accum7', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_gust', models.FloatField(blank=True, null=True)),
                ('obs_time', models.BigIntegerField(blank=True, null=True)),
                ('state_summary', models.SmallIntegerField(blank=True, null=True)),
                ('utc_time', models.DateTimeField(blank=True, null=True)),
                ('unix_time', models.IntegerField(blank=True, null=True)),
                ('dew_point', models.FloatField(blank=True, null=True)),
                ('temp_min', models.FloatField(blank=True, null=True)),
                ('temp_max', models.FloatField(blank=True, null=True)),
                ('sub_type', models.IntegerField(blank=True, null=True)),
                ('lat', models.IntegerField(blank=True, null=True)),
                ('lon', models.IntegerField(blank=True, null=True)),
                ('weather_phenomena', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sandbox_drizzle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StormglassResponseCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_stormg', models.JSONField()),
                ('created_time', models.DateTimeField()),
                ('utc_time', models.DateTimeField()),
                ('timezone', models.SmallIntegerField()),
                ('location_api', models.CharField(blank=True, max_length=100, null=True)),
                ('location_driz', models.CharField(blank=True, max_length=100, null=True)),
                ('unix_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stormglass_response_current',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TomorrowResponseCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_tomorr', models.JSONField()),
                ('created_time', models.DateTimeField()),
                ('utc_time', models.DateTimeField()),
                ('location_api', models.CharField(blank=True, max_length=100, null=True)),
                ('location_driz', models.CharField(blank=True, max_length=100, null=True)),
                ('unix_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tomorrow_response_current',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisualcrossingResponseCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_visualcrossing', models.JSONField()),
                ('created_time', models.DateTimeField()),
                ('utc_time', models.DateTimeField()),
                ('location_api', models.CharField(blank=True, max_length=100, null=True)),
                ('location_driz', models.CharField(blank=True, max_length=100, null=True)),
                ('unix_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'visualcrossing_response_current',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WbitResponseCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_wbit', models.JSONField()),
                ('created_time', models.DateTimeField()),
                ('utc_time', models.DateTimeField()),
                ('timezone', models.SmallIntegerField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('unix_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wbit_response_current',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherApiResponseCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_we_api', models.JSONField()),
                ('created_time', models.DateTimeField()),
                ('utc_time', models.DateTimeField()),
                ('location_api', models.CharField(blank=True, max_length=100, null=True)),
                ('location_driz', models.CharField(blank=True, max_length=100, null=True)),
                ('unix_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weather_api_response_current',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherstackRespCurr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_ws', models.JSONField()),
                ('created_time', models.DateTimeField()),
                ('utc_time', models.DateTimeField()),
                ('timezone', models.CharField(max_length=35)),
                ('location_api', models.CharField(max_length=100)),
                ('unix_time', models.IntegerField(blank=True, null=True)),
                ('location_driz', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'weatherstack_resp_curr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WindyResponseCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_windy', models.JSONField()),
                ('created_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'windy_response_current',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WwoResponseCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_wwo', models.JSONField()),
                ('created_time', models.DateTimeField()),
                ('utc_time', models.DateTimeField()),
                ('location_api', models.CharField(blank=True, max_length=100, null=True)),
                ('location_driz', models.CharField(blank=True, max_length=100, null=True)),
                ('unix_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wwo_response_current',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YadResponseCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_yad', models.JSONField()),
                ('created_time', models.DateTimeField()),
                ('utc_time', models.DateTimeField()),
                ('timezone', models.SmallIntegerField()),
                ('location_api', models.CharField(max_length=100)),
                ('location_driz', models.CharField(blank=True, max_length=100, null=True)),
                ('unix_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'yad_response_current',
                'managed': False,
            },
        ),
    ]
